#!/bin/sh

case $1 in
	start)
		mkdir /var/log/apache2
		service apache2 start

		python /etc/daarrt/scripts/init.py start
		mjpg_streamer -i "/usr/lib/input_uvc.so -d /dev/video0  -y -r 640x480 -f 10" -o "/usr/lib/output_http.so -p 8090 -w /var/www/mjpg_streamer" &
	;;
	stop)
		python /etc/daarrt/scripts/init.py stop
		sudo service shellinabox stop
		killall mjpg_streamer
	;;
	reload|restart)
		sudo service apache2 restart
		sudo service shellinabox restart
		python /etc/daarrt/scripts/init.py start
		killall mjpg_streamer
		mjpg_streamer -i "/usr/lib/input_uvc.so -d /dev/video0  -y -r 640x480 -f 10" -o "/usr/lib/output_http.so -p 8090 -w /var/www/mjpg_streamer" &
	;;
	status)
		echo "Checking DAARRT status..."
		sudo service apache2 status
		sudo service shellinabox status

		# Partie non testee
		echo "Checking mjpeg-streamer process..."
		ps -A | grep mjpeg-streamer
		# Fin partie non testee
	;;
	*)
		log_success_msg "Usage: /etc/init.d/daarrt {start|stop|restart|reload|status}"
		exit 1
	;;
esac
exit 0
# 
