#!/bin/sh

case $1 in
	start)
		python /etc/daarrt/scripts/init.py start
		sudo -u ubuntu cvlc v4l2:///dev/video0 :v4l2-standard= :input-slave=alsa://hw:0,0 :live-caching=300 :sout="#transcode{vcodec=WMV2,vb=800,scale=1,acodec=wma2,ab=128,channels=2,samplerate=44100}:http{dst=:8080/webcam.wmv}" :sout-all :ttl=5 :sout-keep
	;;
	stop)
		python /etc/daarrt/scripts/init.py stop
		killall vlc
	;;
	reload|restart)
		sudo service apache2 restart
		sudo service shellinabox restart
		python /etc/daarrt/scripts/init.py start
		killall vlc
		sudo -u ubuntu cvlc v4l2:///dev/video0 :v4l2-standard= :input-slave=alsa://hw:0,0 :live-caching=300 :sout="#transcode{vcodec=WMV2,vb=800,scale=1,acodec=wma2,ab=128,channels=2,samplerate=44100}:http{dst=:8080/webcam.wmv}" :sout-all :ttl=5 :sout-keep
	;;
	status)
		echo "Checking DAARRT status..."
		sudo service apache2 status
		sudo service shellinabox status
	;;
	*)
		log_success_msg "Usage: /etc/init.d/daarrt {start|stop|restart|reload|status}"
		exit 1
	;;
esac
exit 0
